[package]
name = "utc-datetime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
derive_more = { version = "0.99", features = ["add", "mul", "from", "into"] }
