name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # CI fail on all warnings
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Clippy
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt --all --check

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Doc
      run: cargo doc

  doc-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Doc
      run: cargo doc --no-default-features

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build

  build-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --no-default-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test

  test-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --no-default-features
